
-- Create tables --
CREATE TABLE IF NOT EXISTS answer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    uuid UUID DEFAULT gen_random_uuid(),
    title character varying(255) NOT NULL,
    value bigint NOT NULL,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT answer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS project
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    uuid UUID DEFAULT gen_random_uuid(),
    name character varying(255) NOT NULL,
    is_engine_active boolean NOT NULL DEFAULT false,
    send_date TIMESTAMP,
    next_send_date TIMESTAMP ,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT project_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS question_category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    uuid UUID DEFAULT gen_random_uuid(),
    title character varying(255) NOT NULL,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT question_category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quiz
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    uuid UUID DEFAULT gen_random_uuid(),
    is_active boolean ,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT quiz_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS app_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    uuid UUID DEFAULT gen_random_uuid(),
    first_name character varying(255),
    last_name character varying(255),
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT app_user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS subscriber
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    uuid UUID DEFAULT gen_random_uuid(),
    first_name character varying(255),
    last_name character varying(255),
    email character varying(255) NOT NULL,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT subscriber_pkey PRIMARY KEY (id)
 );

CREATE TABLE IF NOT EXISTS project_subscriber
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    project_id bigint,
    subscriber_id bigint,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT project_subscriber_pkey PRIMARY KEY (id),
    CONSTRAINT project_subscriber_project_fk FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT project_subscriber_subscriber_fk FOREIGN KEY (subscriber_id) REFERENCES subscriber (id)
);

CREATE TABLE IF NOT EXISTS project_app_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app_user_id bigint,
    project_id bigint,
    is_owner boolean,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT project_app_user_pkey PRIMARY KEY (id),
    CONSTRAINT project_app_user_project_fk FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT project_app_user_app_user_fk FOREIGN KEY (app_user_id) REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS project_quiz
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    project_id bigint NOT NULL,
    quiz_id bigint NOT NULL,
    is_sent boolean DEFAULT FALSE,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT project_quiz_pkey PRIMARY KEY (id),
    CONSTRAINT project_quiz_project_fk FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT project_quiz_quiz_fk FOREIGN KEY (quiz_id) REFERENCES quiz (id)
);

CREATE TABLE IF NOT EXISTS question
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    uuid UUID DEFAULT gen_random_uuid(),
    content character varying(255) NOT NULL,
    category_id bigint,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT question_pkey PRIMARY KEY (id),
    CONSTRAINT question_category_fk FOREIGN KEY (category_id) REFERENCES question_category (id)
);

CREATE TABLE IF NOT EXISTS question_config
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    question_id bigint NOT NULL,
    answer_id bigint NOT NULL,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT question_config_pkey PRIMARY KEY (id),
    CONSTRAINT question_config_answer_fk FOREIGN KEY (answer_id) REFERENCES answer (id),
    CONSTRAINT question_config_question_fk FOREIGN KEY (question_id) REFERENCES question (id)
);

CREATE TABLE IF NOT EXISTS question_quiz
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    uuid UUID DEFAULT gen_random_uuid(),
    quiz_id bigint NOT NULL,
    question_id bigint NOT NULL,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT question_quiz_pkey PRIMARY KEY (id),
    CONSTRAINT question_quiz_question_fk FOREIGN KEY (question_id) REFERENCES question (id),
    CONSTRAINT question_quiz_quiz_fk FOREIGN KEY (quiz_id) REFERENCES quiz (id)
);

CREATE TABLE IF NOT EXISTS answer_stat
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    project_id bigint,
    question_category_id bigint,
    category_kpi character varying(255),
    from_date TIMESTAMP NOT NULL,
    to_date TIMESTAMP NOT NULL,
    is_verified boolean DEFAULT FALSE,
    ins_date TIMESTAMP NOT NULL DEFAULT NOW(),
    avg_value numeric(2,1),
    CONSTRAINT answer_stat_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS answer_log
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    project_id bigint,
    question_category_id bigint,
    question_id bigint,
    question_quiz_id bigint,
    answer_value bigint,
    question_content character varying(255),
    ins_date TIMESTAMP NOT NULL,
    CONSTRAINT answer_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS answer_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    quiz_id bigint,
    app_user_id bigint,
    project_id bigint NOT NULL,
    ins_date TIMESTAMP NOT NULL,
    CONSTRAINT answer_user_pkey PRIMARY KEY (id)
);




