-- CREATE TABLES  --
CREATE TABLE IF NOT EXISTS privilege
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) NOT NULL,
    CONSTRAINT privilege_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS roles_privileges
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    privilege_id BIGINT,
    role_id BIGINT,
    CONSTRAINT roles_privileges_pkey PRIMARY KEY (id),
    CONSTRAINT roles_privileges_privilege_fk FOREIGN KEY (privilege_id) REFERENCES privilege (id),
    CONSTRAINT roles_privileges_role_fk FOREIGN KEY (role_id) REFERENCES role (id)
);

-- ADD NEW FOREIGN KEY --
ALTER TABLE IF EXISTS project_app_user
    ADD COLUMN IF NOT EXISTS role_id BIGINT,
    ADD CONSTRAINT project_app_user_role_fk
    FOREIGN KEY (role_id) REFERENCES  role (id);

-- INSERT DEFAULT ROLES --
INSERT INTO  role (name) values
    ('ADMIN'),          -- ACCESS and RIGHTS to everything                                                   --
    ('MANAGER'),        -- ACCESS only to his projects and full RIGHTS to project, team members, subscribers --
    ('TEAM_MEMBER'),    -- ACCESS to quizzes and RIGHTS of reading and submitting the quizzes                --
    ('SUBSCRIBER')      -- ACCESS to dashboard where is subscribed and only read RIGHTS to dashboard/reports --


